export type PermissionDefinition = {
  key: string;
  group: string;
  label: string;
};

export const PERMISSION_CATALOG = [
  { key: 'users.read', group: 'Tài khoản', label: 'Xem tài khoản' },
  { key: 'users.create', group: 'Tài khoản', label: 'Tạo tài khoản' },
  { key: 'users.update', group: 'Tài khoản', label: 'Cập nhật tài khoản' },
  { key: 'users.delete', group: 'Tài khoản', label: 'Khóa tài khoản' },
  { key: 'roles.read', group: 'Vai trò', label: 'Xem vai trò' },
  { key: 'roles.update', group: 'Vai trò', label: 'Cập nhật vai trò' },
  { key: 'permissions.read', group: 'Vai trò', label: 'Xem danh mục quyền' },
  { key: 'cooperatives.read', group: 'HTX', label: 'Xem HTX' },
  { key: 'cooperatives.create', group: 'HTX', label: 'Tạo HTX' },
  { key: 'cooperatives.update', group: 'HTX', label: 'Cập nhật HTX' },
  { key: 'cooperatives.delete', group: 'HTX', label: 'Xóa/ngừng HTX' },
  { key: 'cooperatives.assign_admin', group: 'HTX', label: 'Gán Admin HTX' },
  { key: 'subscription_plans.read', group: 'Gói SaaS', label: 'Xem gói' },
  { key: 'subscription_plans.create', group: 'Gói SaaS', label: 'Tạo gói' },
  { key: 'subscription_plans.update', group: 'Gói SaaS', label: 'Cập nhật gói' },
  { key: 'subscription_plans.delete', group: 'Gói SaaS', label: 'Xóa gói' },
  { key: 'subscriptions.read', group: 'Gói SaaS', label: 'Xem gói HTX' },
  { key: 'subscriptions.assign', group: 'Gói SaaS', label: 'Gán gói HTX' },
  { key: 'subscriptions.update', group: 'Gói SaaS', label: 'Cập nhật gói HTX' },
  { key: 'subscriptions.renew', group: 'Gói SaaS', label: 'Gia hạn gói HTX' },
  { key: 'subscriptions.cancel', group: 'Gói SaaS', label: 'Hủy gói HTX' },
  { key: 'invoices.read', group: 'Hóa đơn', label: 'Xem hóa đơn' },
  { key: 'invoices.create', group: 'Hóa đơn', label: 'Tạo hóa đơn' },
  { key: 'invoices.update', group: 'Hóa đơn', label: 'Cập nhật hóa đơn' },
  { key: 'invoices.mark_paid', group: 'Hóa đơn', label: 'Đánh dấu đã thu' },
  { key: 'invoices.mark_unpaid', group: 'Hóa đơn', label: 'Đánh dấu chưa thu' },
  { key: 'invoices.cancel', group: 'Hóa đơn', label: 'Hủy hóa đơn' },
  { key: 'payments.read', group: 'Thanh toán', label: 'Xem thanh toán' },
  { key: 'product_categories.read', group: 'Danh mục sản phẩm', label: 'Xem danh mục' },
  { key: 'product_categories.create', group: 'Danh mục sản phẩm', label: 'Tạo danh mục' },
  { key: 'product_categories.delete', group: 'Danh mục sản phẩm', label: 'Xóa danh mục' },
  { key: 'products.read', group: 'Sản phẩm', label: 'Xem sản phẩm' },
  { key: 'products.create', group: 'Sản phẩm', label: 'Tạo sản phẩm' },
  { key: 'products.update', group: 'Sản phẩm', label: 'Cập nhật sản phẩm' },
  { key: 'products.delete', group: 'Sản phẩm', label: 'Xóa sản phẩm' },
  { key: 'certifications.read', group: 'Chứng nhận', label: 'Xem chứng nhận' },
  { key: 'certifications.create', group: 'Chứng nhận', label: 'Tạo chứng nhận' },
  { key: 'certifications.update', group: 'Chứng nhận', label: 'Cập nhật chứng nhận' },
  { key: 'certifications.delete', group: 'Chứng nhận', label: 'Xóa chứng nhận' },
  { key: 'zones.read', group: 'Vùng trồng', label: 'Xem vùng trồng' },
  { key: 'zones.create', group: 'Vùng trồng', label: 'Tạo vùng trồng' },
  { key: 'zones.update', group: 'Vùng trồng', label: 'Cập nhật vùng trồng' },
  { key: 'zones.delete', group: 'Vùng trồng', label: 'Xóa vùng trồng' },
  { key: 'crop_types.read', group: 'Danh mục cây trồng', label: 'Xem loại cây' },
  { key: 'crop_types.create', group: 'Danh mục cây trồng', label: 'Tạo loại cây' },
  { key: 'crop_types.update', group: 'Danh mục cây trồng', label: 'Cập nhật loại cây' },
  { key: 'crop_types.delete', group: 'Danh mục cây trồng', label: 'Ẩn loại cây' },
  { key: 'trees.read', group: 'Hộ chiếu cây', label: 'Xem cây' },
  { key: 'trees.create', group: 'Hộ chiếu cây', label: 'Tạo cây' },
  { key: 'trees.update', group: 'Hộ chiếu cây', label: 'Cập nhật cây' },
  { key: 'trees.delete', group: 'Hộ chiếu cây', label: 'Lưu trữ cây' },
  { key: 'tree_events.read', group: 'Nhật ký cây', label: 'Xem nhật ký cây' },
  { key: 'tree_events.create', group: 'Nhật ký cây', label: 'Tạo nhật ký cây' },
  { key: 'tree_events.update', group: 'Nhật ký cây', label: 'Cập nhật nhật ký cây' },
  { key: 'tree_events.delete', group: 'Nhật ký cây', label: 'Lưu trữ nhật ký cây' },
  { key: 'seasons.read', group: 'Mùa vụ', label: 'Xem mùa vụ' },
  { key: 'seasons.create', group: 'Mùa vụ', label: 'Tạo mùa vụ' },
  { key: 'seasons.update', group: 'Mùa vụ', label: 'Cập nhật mùa vụ' },
  { key: 'harvests.read', group: 'Thu hoạch', label: 'Xem thu hoạch' },
  { key: 'harvests.create', group: 'Thu hoạch', label: 'Tạo thu hoạch' },
  { key: 'harvests.update', group: 'Thu hoạch', label: 'Cập nhật thu hoạch' },
  { key: 'lots.read', group: 'Lô sản phẩm', label: 'Xem lô sản phẩm' },
  { key: 'lots.create', group: 'Lô sản phẩm', label: 'Tạo lô sản phẩm' },
  { key: 'lots.update', group: 'Lô sản phẩm', label: 'Cập nhật lô sản phẩm' },
  { key: 'lots.delete', group: 'Lô sản phẩm', label: 'Lưu trữ lô sản phẩm' },
  { key: 'product_batches.read', group: 'Sản phẩm truy xuất', label: 'Xem ProductBatch' },
  { key: 'product_batches.create', group: 'Sản phẩm truy xuất', label: 'Tạo ProductBatch' },
  { key: 'product_batches.update', group: 'Sản phẩm truy xuất', label: 'Cập nhật ProductBatch' },
  { key: 'product_batches.delete', group: 'Sản phẩm truy xuất', label: 'Lưu trữ ProductBatch' },
  { key: 'traceability_codes.read', group: 'Mã truy xuất', label: 'Xem mã truy xuất' },
  { key: 'traceability_codes.create', group: 'Mã truy xuất', label: 'Cấp mã truy xuất' },
  { key: 'traceability_codes.update', group: 'Mã truy xuất', label: 'Cập nhật mã truy xuất' },
  { key: 'traceability_codes.delete', group: 'Mã truy xuất', label: 'Ẩn mã truy xuất' },
  { key: 'farming_logs.read', group: 'Nhật ký canh tác', label: 'Xem nhật ký' },
  { key: 'farming_logs.create', group: 'Nhật ký canh tác', label: 'Tạo nhật ký' },
  { key: 'farming_logs.update', group: 'Nhật ký canh tác', label: 'Cập nhật nhật ký' },
  { key: 'farming_logs.delete', group: 'Nhật ký canh tác', label: 'Xóa nhật ký' },
  { key: 'passports.read', group: 'QR Passport', label: 'Xem QR Passport' },
  { key: 'passports.create', group: 'QR Passport', label: 'Tạo QR Passport' },
  { key: 'passports.update', group: 'QR Passport', label: 'Cập nhật QR Passport' },
  { key: 'passports.delete', group: 'QR Passport', label: 'Xóa QR Passport' },
  { key: 'files.read', group: 'Tệp', label: 'Xem tệp' },
  { key: 'files.upload', group: 'Tệp', label: 'Upload tệp' },
  { key: 'files.delete', group: 'Tệp', label: 'Xóa tệp' },
  { key: 'orders.read', group: 'Đơn hàng', label: 'Xem đơn hàng' },
  { key: 'orders.create', group: 'Đơn hàng', label: 'Tạo đơn hàng' },
  { key: 'orders.update', group: 'Đơn hàng', label: 'Cập nhật đơn hàng' },
  { key: 'news.read', group: 'Tin tức', label: 'Xem tin tức' },
  { key: 'news.create', group: 'Tin tức', label: 'Tạo tin tức' },
  { key: 'news.update', group: 'Tin tức', label: 'Cập nhật tin tức' },
  { key: 'news.delete', group: 'Tin tức', label: 'Ẩn/xóa tin tức' },
  { key: 'reports.overview', group: 'Báo cáo', label: 'Xem tổng quan' },
  { key: 'reports.revenue', group: 'Báo cáo', label: 'Xem doanh thu' },
  { key: 'reports.snapshots', group: 'Báo cáo', label: 'Tạo snapshot báo cáo' },
  { key: 'settings.read', group: 'Hệ thống', label: 'Xem cài đặt' },
  { key: 'settings.update', group: 'Hệ thống', label: 'Cập nhật cài đặt' },
  { key: 'contacts.read', group: 'Liên hệ', label: 'Xem liên hệ public' },
  { key: 'contacts.update', group: 'Liên hệ', label: 'Cập nhật trạng thái liên hệ' },
  { key: 'audit_logs.read', group: 'Hệ thống', label: 'Xem nhật ký hệ thống' },
  { key: 'backups.read', group: 'Sao lưu', label: 'Xem backup' },
  { key: 'backups.create', group: 'Sao lưu', label: 'Tạo backup' },
  { key: 'backups.download', group: 'Sao lưu', label: 'Tải backup' },
  { key: 'backups.restore', group: 'Sao lưu', label: 'Khôi phục backup' },
  { key: 'notifications.read', group: 'Thông báo', label: 'Xem thông báo' },
  { key: 'notifications.create', group: 'Thông báo', label: 'Tạo thông báo' },
  { key: 'notifications.update', group: 'Thông báo', label: 'Cập nhật thông báo' }
] satisfies PermissionDefinition[];

export const PERMISSION_KEYS = PERMISSION_CATALOG.map((item) => item.key);

export function hasPermission(granted: string[], required: string) {
  if (granted.includes('*') || granted.includes(required)) return true;
  const [namespace] = required.split('.');
  return granted.includes(`${namespace}.*`);
}

export function wildcardPermissions() {
  return Array.from(new Set(PERMISSION_KEYS.map((key) => `${key.split('.')[0]}.*`).concat('system.*')));
}
