ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'SHIPPING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';

ALTER TABLE "orders" ADD COLUMN "buyerName" TEXT;
ALTER TABLE "orders" ADD COLUMN "buyerPhone" TEXT;
ALTER TABLE "orders" ADD COLUMN "buyerEmail" TEXT;
ALTER TABLE "orders" ADD COLUMN "province" TEXT;
ALTER TABLE "orders" ADD COLUMN "district" TEXT;
ALTER TABLE "orders" ADD COLUMN "ward" TEXT;
ALTER TABLE "orders" ADD COLUMN "address" TEXT;
ALTER TABLE "orders" ADD COLUMN "paymentMethod" TEXT DEFAULT 'COD';
